services:
  api_zorro_scape:
    build: .
    restart: always
    container_name: api_zorro_scape
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DATA_PATH=current_status/